TuMvcApp/Models/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TuMvcApp.Models
{
	public class CategoryModel
	{
		public int? Id { get; set; }

		public int? ParentId { get; set; }
		
		public string Name { get; set; }
	}
}

TuMvcApp/Models/CourseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TuMvcApp.Models
{
	public class CourseModel
	{
		public int? Id { get; set; }

		public string Title { get; set; }

		public int CategoryId { get; set; }

		public CategoryModel Category { get; set; }

		public string Description { get; set; }

		public int AccessMode { get; set; }

		public DateTime StartDate { get; set; }

		public DateTime EndDate { get; set; }

		public int PublishedBy { get; set; }

		public DateTime DatePublished { get; set; }

		public DateTime DateModified { get; set; }

		public int Duration { get; set; }

		public string CourseImage { get; set; }

		public int CourseTypeId { get; set; }

	}
}

TuMvcApp/Models/ErrorViewModel.cs
using System;

namespace TuMvcApp.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TuMvcApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TuMvcApp.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TuMvcApp/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TuMvcApp.Controllers
{
	[Route("auth")]
	public class AuthController : Controller
	{
		[Route("signin")]
		public IActionResult signin(string returnUrl = null)
		{
			//return Challenge(new AuthenticationProperties { RedirectUri = returnUrl ?? "/home" });
			return Redirect("~/home");
		}
	}
}

TuMvcApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using TuMvcApp.Services;

namespace TuMvcApp.Controllers
{
	public class CategoriesController : Controller
	{
		private readonly IHttpClientFactory _httpClientFactory;
		private readonly IHostingEnvironment _he;
		private readonly string apiEndPoint;
		private ApiEndPointSettings _appSettings { get; set; }

		public CategoriesController(IHttpClientFactory httpClientFactory, IHostingEnvironment he, IOptions<ApiEndPointSettings> appSettings)
		{
			_httpClientFactory = httpClientFactory;
			_he = he;
			_appSettings = appSettings.Value;

			if (_he.IsDevelopment())
				apiEndPoint = _appSettings.Dev;
			else
				apiEndPoint = _appSettings.Cloud;
		}
		// GET: Categories
		public ActionResult Index()
		{
			return View();
		}

		// GET: Categories/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: Categories/Create
		public ActionResult Create()
		{
			return View();
		}

		// GET: Categories/Edit/1
		public async Task<IActionResult> Edit(int id)
		{

			var client = _httpClientFactory.CreateClient();
			client.BaseAddress = new Uri(apiEndPoint);

			var result = await client.GetStringAsync("/api/Categories/Get?id=" + id);

			return PartialView("~/Views/Categories/_edit.cshtml", JsonConvert.DeserializeObject(result));
		}

		//// POST: Categories/Create
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public ActionResult Create(IFormCollection collection)
		//{
		//    try
		//    {
		//        // TODO: Add insert logic here

		//        return RedirectToAction(nameof(Index));
		//    }
		//    catch
		//    {
		//        return View();
		//    }
		//}

		//// GET: Categories/Edit/5
		//public ActionResult Edit(int id)
		//{
		//    return View();
		//}

		//// POST: Categories/Edit/5
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public ActionResult Edit(int id, IFormCollection collection)
		//{
		//    try
		//    {
		//        // TODO: Add update logic here

		//        return RedirectToAction(nameof(Index));
		//    }
		//    catch
		//    {
		//        return View();
		//    }
		//}

		//// GET: Categories/Delete/5
		//public ActionResult Delete(int id)
		//{
		//    return View();
		//}

		//// POST: Categories/Delete/5
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public ActionResult Delete(int id, IFormCollection collection)
		//{
		//    try
		//    {
		//        // TODO: Add delete logic here

		//        return RedirectToAction(nameof(Index));
		//    }
		//    catch
		//    {
		//        return View();
		//    }
		//}
	}
}

TuMvcApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using TuMvcApp.Services;

namespace TuMvcApp.Controllers
{
	public class CoursesController : Controller
	{
		private readonly IHttpClientFactory _httpClientFactory;
		private readonly IHostingEnvironment _he;
		private readonly string apiEndPoint;
		private ApiEndPointSettings _apiEndPointSettings { get; set; }

		public CoursesController(IHttpClientFactory httpClientFactory, IHostingEnvironment he, IOptions<ApiEndPointSettings> apiEndPointSettings)
		{
			_httpClientFactory = httpClientFactory;
			_he = he;
			_apiEndPointSettings = apiEndPointSettings.Value;

			if (_he.IsDevelopment())
				apiEndPoint = _apiEndPointSettings.Dev;
			else
				apiEndPoint = _apiEndPointSettings.Cloud;
		}
		public IActionResult Index()
		{
			return View();
		}


		// GET: Courses/Create
		public IActionResult Create()
		{
			return View();
		}

		// GET: Courses/Catalog
		public IActionResult Catalog()
		{
			return View();
		}

		// GET: Courses/Search
		public IActionResult Search(string q)
		{
			return View();
		}

		// GET: Courses/List
		public IActionResult List()
		{
			return View();
		}

		// GET: Courses/Edit/{id}
		public async Task<IActionResult> Edit(int id)
		{
			var client = _httpClientFactory.CreateClient();
			client.BaseAddress = new Uri(apiEndPoint);

			var result = await client.GetStringAsync("/api/Courses/Get/" + id);


			return View(JsonConvert.DeserializeObject(result));
		}
	}
}

TuMvcApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TuMvcApp.Models;

namespace Tu_Mvc.Controllers
{
	public class HomeController : Controller
	{
		
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult About()
		{
			ViewData["Message"] = "Your application description page.";

			return View();
		}

		public IActionResult Contact()
		{
			ViewData["Message"] = "Your contact page.";

			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TuMvcApp/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Tu_Mvc.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/Index.cshtml");
        }
	}
}

TuMvcApp/Views/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a asp-controller="Course" asp-action="Create" type="submit" class="btn btn-info">Create Course</a>

TuMvcApp/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Course</h1>
<a asp-controller="Courses" asp-action="List" type="submit" class="btn btn-info">Courses List</a>
<a asp-controller="Courses" asp-action="Create" type="submit" class="btn btn-info">Create Course</a>

<h1>Categories</h1>
<a asp-controller="Categories" asp-action="Index" type="submit" class="btn btn-info">Categories List</a>
<a asp-controller="Categories" asp-action="Create" type="submit" class="btn btn-info">Create Categories</a>

TuMvcApp/Views/Categories/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<a asp-controller="Categories" asp-action="Index">Back to List</a>

@section Scripts
    {
    <script src="~/js/Categories/Categories.js"></script>
    <script>
        $(document).ready(function () {
            clearCategory();
            loadCategory();

        })
    </script>
}
    <h2>Edit Category </h2>

<hr />

    <div id="formCreateCategory" class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div>
                <ul id="validationSummary"></ul>
            </div>

            <div class="form-group">
                <label class="control-label">Name</label>
                <input id="Name" name="Name" class="form-control" />
            </div>

            @*Category*@
            <div class="form-group row">
                <label for="category" class="col-sm-12 col-form-label">Parent Category:&nbsp; (Select if you want to add as Subcategory)</label>
                <div class="col-sm-12">
                    <div id="category" class="dropdown">
                        <select id="ddCategory" class="form-control">
                            <option value="0" selected="selected"> Select</option>
                            <option value="1"> Category 1</option>
                            <option value="2"> Category 2</option>
                        </select>
                    </div>
                </div>
            </div>

            <input type="submit" id="formCreateCategory" onclick="CreateCategory(); return false;" value="Create" class="btn btn-primary btn-block" />
        </div>
    </div>

TuMvcApp/Views/Categories/Index.cshtml
@page
@{
    //ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
    {
    <script src="~/js/Categories/Categories.js"></script>
    <script>
        $(document).ready(function () {
            loadCategory();
            LoadCategoriesIntoTable("tbl_index_all_categories");

            //Edit form on submit
            $("#partialEditForm").submit(function () {
                let _id, _name, _parentid;
                _id = $('input[name=id]').val().trim();
                _name = $('input[name=name]').val().trim();
                _parentid = parseInt($('#ddCategory').val());
                PostEditCategory(_id, _name, _parentid)
                return false;
            });

        });
    </script>
}

<div class="container">
    <h2>Categories</h2>
    <a asp-controller="Categories" asp-action="Create" type="submit" class="btn btn-info">Create Category</a>
    <br />
    <hr />
    <table id="tbl_index_all_categories" class="display" style="width:100%">
        <thead>
            <tr>
                <th>id</th>
                <th>Name</th>
                <th>ParentId</th>
                <th>Action</th>
            </tr>
        </thead>
        @*<tbody>
            <tr>
                <td>
                    Loading..
                </td>
            </tr>
        </tbody>*@
    </table>

</div>


<div class="modal fade" id="_editCategoriesModal" tabindex="-1" role="dialog" aria-labelledby="_editCategoriesModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form id="partialEditForm">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Edit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="formCreateCategory" class="row justify-content-center align-items-center">
                        <div class="col-md-6">
                            <div>
                                <ul id="validationSummary"></ul>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Name</label>
                                <input id="id" name="id" type="hidden" />
                                <input id="name" name="name" class="form-control" />
                            </div>
                            @*Category*@
                            <div class="form-group row">
                                <label for="category" class="col-sm-12 col-form-label">Parent Category:&nbsp; (Select if you want to add this as Subcategory)</label>
                                <div class="col-sm-12">
                                    <div id="category" class="dropdown">
                                        <select id="ddCategory" class="form-control">
                                            <option value="0" selected="selected"> Select</option>
                                            <option value="1"> Category 1</option>
                                            <option value="2"> Category 2</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            @*onclick="UpdateCategory(); return false;"*@
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" id="formCreateCategory" value="Update" class="btn btn-primary " />
                </div>
            </form>
        </div>
    </div>
</div>

TuMvcApp/Views/Courses/List.cshtml
@page
@section Scripts
    {
    <script src="~/js/Courses/Courses.js"></script>
    <script src="~/js/Categories/Categories.js"></script>
    <script>
        $(document).ready(function () {
            LoadCoursesIntoTable("tbl_index_all_courses");
            initializeImageUploader();
            ////Edit form on submit
            //$("#partialEditForm").submit(function () {
            //    let _id, _name, _parentid;
            //    _id = $('input[name=id]').val().trim();
            //    _name = $('input[name=name]').val().trim();
            //    _parentid = parseInt($('#ddCategory').val());
            //    PostEditCategory(_id, _name, _parentid)
            //    return false;
            //});

        });
    </script>
}

<div class="container">
    <h2>Categories</h2>
    <a asp-controller="Courses" asp-action="Create" type="submit" class="btn btn-info">Create Course</a>
    <br />
    <hr />
    <table id="tbl_index_all_courses" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Course Type</th>
                <th>Title</th>
                <th>Description</th>
                <th>Category</th>
                <th>Subcategory</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>

</div>


@*<div class="modal fade" id="_editCourseModal" tabindex="-1" role="dialog" aria-labelledby="_editCourseModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit - <label id="lblCourseName">{Course Name}</label></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
               
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input type="submit" id="formEditCourse" onclick="postUpdateCourse(); return false;" value="Update" class="btn btn-primary " />
            </div>

        </div>
    </div>
</div>*@

TuMvcApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

TuMvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Home</h1>

WLCM

TuMvcApp/Views/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tu_Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/landingpage.css" />


    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/landingpage.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-transparent">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="btn btn-outline-primary btn-sm" asp-controller="Auth" asp-action="signin" asp-route-returnUrl="@Context.Request.Query["returnUrl"]">Login</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container h-75 ">
        <div class="row h-75 justify-content-center align-items-center m-5">
            @*<img src="~/images/logo.png" alt="Alternate Text" width="50%" />*@
            <h1><b>T:University</b></h1>

            <div id="frmSearchCourse" class="col-12 ">
                <div class="form-group">
                    <input name="q" type="text" class="form-control" id="txtSearch" placeholder="Search Course" onkeypress="detectEnterKey(event)">
                </div>
            </div>
        </div>
    </div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function detectEnterKey(e) {
            if (e.keyCode == 13) {
                var searchString = $("#txtSearch").val().trim();
                searchCourse(searchString);
            }
        }
    </script>
</body>
</html>

TuMvcApp/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tu_Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        @*<link rel="stylesheet" href="~/lib/spin-js/spin.css" />*@
        <link rel="stylesheet" href="~/lib/tempusdominus-datepicker/tempusdominus-bootstrap-4.min.css" />
        <link rel="stylesheet" href="~/lib/animate/animate.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("styles", false)
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-brand" href="/"><img src="~/images/logo.png" alt="Alternate Text" width="300px" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="form-inline my-6 my-lg-0 input-group w-50">
                <input id="txtSearch" class="form-control border-radius-0 border-right-0" type="search" placeholder="Search" aria-label="Search" onkeypress="detectEnterKey(event);">
                <div class="input-group-append">
                    <button class="btn border bg-transparent border-left-0 border-radius-0 cursor-pointer" onclick="searchClick();">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
            &nbsp;
            &nbsp;
            &nbsp;
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Courses" asp-action="Catalog"> <i class="fas fa-list"></i> Course Catalog</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-chart-bar"></i> Dashboard
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link" href="#"> Learner</a>
                        <a class="nav-link" asp-controller="Admin" asp-action="Index"> Admin</a>
                    </div>
                </li>
            </ul>

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container container-lg body-content">
        @RenderBody()


    </div>
    @*<footer class="bg-dark">
            <p class="text-white">&copy; 2019 - Tu_Mvc</p>
        </footer>*@


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        @*<script src="~/lib/spin-js/spin.js"></script>*@
        <script src="~/lib/sweet-alert/sweetalert.min.js"></script>
        <script src="~/lib/momentjs/moment.js"></script>
        <script src="~/lib/tempusdominus-datepicker/tempusdominus-bootstrap-4.min.js"></script>
        <script src="~/lib/lazyload-js/lazyload.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@11.0.6/dist/lazyload.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

    @*set variables for dev environment*@
    <environment include="Development">
        <script>  var apiEndpoint = "@Configuration["ApiEndpoint:Dev"]";</script>
    </environment>
    @*set variables for cloud environment*@
    <environment exclude="Development">
        <script>  var apiEndpoint = "@Configuration["ApiEndpoint:Cloud"]";</script>
    </environment>
    <script>


        var searchString;

        function searchClick() {
            debugger;
            searchString = $("#txtSearch").val().trim();
            searchCourse(searchString);
        }

        function detectEnterKey(e) {
            if (e.keyCode == 13) {
                searchString = $("#txtSearch").val().trim();
                searchCourse(searchString);
            }
        }
    </script>
    @RenderSection("Scripts", required: false)

</body>
</html>